name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  process_run: ^1.2.4
  path: ^1.9.1
  cron: ^0.6.2
  http: ^1.4.0
  shelf: ^1.4.2
  dart_firebase_admin: ^0.4.1
  logger: ^2.6.1
  intl: ^0.20.2
  shelf_router: ^1.1.4

  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.5.4
  shelf_router_generator: ^1.1.1